name: Auto Generate README

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python generate_readme.py

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Auto update README"
          git push
